### ISSUE TITLE
Prepackaged tor does not work

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#3937] opened 2021-12-24 04:36 UTC
When running bitcoin-s bundle without tor already installed it does not work

**Comment by rorp** [comment] 2021-12-28 20:44
It works as expected for me on Mac OS X 11.6

How to reproduce it?

**Comment by benthecarman** [comment] 2021-12-28 20:48
We we're getting issues when tor wasn't installed. It would say the TorController cannot connect

**Comment by rorp** [comment] 2021-12-29 22:03
So here's what I'm doing.

1. backup `~/.bitcoins` and remove it
2. download the installer from https://github.com/bitcoin-s/bitcoin-s/actions/runs/1634111119
3. install the bundle
4. start the app
5. on `Welcome to Bitcoin-S` click `Launch Wallet` button 
![image](https://user-images.githubusercontent.com/2314888/147706770-e81e3b4e-7206-4692-a5eb-ce12d0aec102.png)
6. prepackaged tor starts and the wallet screen appears 
![image](https://user-images.githubusercontent.com/2314888/147706792-97a4aff6-3fd3-4d42-94fb-a0c8770bdd35.png)

What step are required to reproduce the issue?

**Comment by benthecarman** [comment] 2021-12-30 03:38
Hmm I can't reproduce locally anymore. It was happening on a fresh install of ubuntu before I had even installed tor. Installing tor later fixed it.

I tried stopping tor in systemd and renaming the tor binaries on my `PATH` but not getting the issues. Maybe related to something else that is installed with tor

**Comment by Christewart** [comment] 2022-01-30 15:47
I'm closing this for now as we can't reproduce

**Closed as completed by Christewart** 2022-01-30 15:47 UTC
Labels: bug, tor
