### ISSUE TITLE
No sync happens on fresh regtest

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#1741] opened 2020-08-03 15:35 UTC
I have 110 blocks on my regtest bitcoind instance, i startup my neutrino node and attempt to sync and I get disconnected. 
Here is the logs:
```
2020-08-03T14:59:57 INFO [HTTP] Initialized chain api
2020-08-03T14:59:57 INFO [WALLET] Using pre-existing wallet
2020-08-03T14:59:57 INFO [P2P] Starting node
2020-08-03T14:59:57 INFO [P2P] Attempting to connect to peer=localhost/127.0.0.1:18444
2020-08-03T14:59:57 DEBUG [P2P] Tcp connection to: localhost/127.0.0.1:18444
2020-08-03T14:59:57 DEBUG [P2P] Local: /127.0.0.1:53142
2020-08-03T14:59:57 INFO [P2P] Connection established with peer=Peer(localhost/127.0.0.1:18444)
2020-08-03T14:59:57 DEBUG [P2P] Sending msg=version to peer=localhost/127.0.0.1:18444
2020-08-03T14:59:58 DEBUG [P2P] Received 151 TCP bytes
2020-08-03T14:59:58 DEBUG [P2P] Parsed 2 message(s) from bytes: NetworkMessage(NetworkHeader(RegTest,version,UInt32Impl(103),ByteVector(4 bytes, 0x30083be3)), VersionMessage(ProtocolVersion70015, ServiceIdentifier(network=true, compactFilters=false, getUtxo=false, bloom=false, witness=true, xthin=false, networkLimited=true), epoch=1596466798, receiverServices=/0:0:0:0:0:0:0:0, receiverAddress=/0:0:0:0:0:0:0:0, receiverPort=0), userAgent=/Satoshi:0.18.99/, startHeight=210, relay=true)), NetworkMessage(NetworkHeader(RegTest,verack,UInt32Impl(0),ByteVector(4 bytes, 0x5df6e0e2)), VerAckMessage)
2020-08-03T14:59:58 DEBUG [P2P] Unaligned bytes after this: 0
2020-08-03T14:59:58 DEBUG [P2P] Received message=version from peer=Peer(localhost/127.0.0.1:18444) state=Initializing 
2020-08-03T14:59:58 DEBUG [P2P] Sending msg=verack to peer=localhost/127.0.0.1:18444
2020-08-03T14:59:58 DEBUG [P2P] Received message=verack from peer=Peer(localhost/127.0.0.1:18444) state=Initializing 
2020-08-03T14:59:58 DEBUG [P2P] Received 143 TCP bytes
2020-08-03T14:59:58 DEBUG [P2P] Parsed 4 message(s) from bytes: NetworkMessage(NetworkHeader(RegTest,sendheaders,UInt32Impl(0),ByteVector(4 bytes, 0x5df6e0e2)), SendHeadersMessage), NetworkMessage(NetworkHeader(RegTest,ping,UInt32Impl(8),ByteVector(4 bytes, 0xd80ab417)), PingMessageImpl(UInt64Impl(613932674654868392))), NetworkMessage(NetworkHeader(RegTest,addr,UInt32Impl(31),ByteVector(4 bytes, 0x56d09231)), AddrMessageImpl(CompactSizeUInt(1),List(NetworkIpAddressImpl(UInt32Impl(1596466798),ServiceIdentifier(network=true, compactFilters=false, getUtxo=false, bloom=false, witness=true, xthin=false, networkLimited=true),/2601:282:4100:d070:0:0:0:875d,18444)))), NetworkMessage(NetworkHeader(RegTest,feefilter,UInt32Impl(8),ByteVector(4 bytes, 0xe80fd19f)), FeeFilterMessageImpl(SatoshisPerKiloByte(-1728537831980138496 sats)))
2020-08-03T14:59:58 DEBUG [P2P] Unaligned bytes after this: 0
2020-08-03T14:59:58 DEBUG [P2P] Received message=sendheaders from peer=Peer(localhost/127.0.0.1:18444) state=Normal 
2020-08-03T14:59:58 DEBUG [P2P] Sending msg=sendheaders to peer=localhost/127.0.0.1:18444
2020-08-03T14:59:58 DEBUG [P2P] Received message=ping from peer=Peer(localhost/127.0.0.1:18444) state=Normal 
2020-08-03T14:59:58 DEBUG [P2P] Sending msg=pong to peer=localhost/127.0.0.1:18444
2020-08-03T14:59:58 DEBUG [P2P] Received message=addr from peer=Peer(localhost/127.0.0.1:18444) state=Normal 
2020-08-03T14:59:58 DEBUG [P2P] Received message=feefilter from peer=Peer(localhost/127.0.0.1:18444) state=Normal 
2020-08-03T14:59:58 INFO [P2P] Our peer=Peer(localhost/127.0.0.1:18444) has been initialized
2020-08-03T14:59:58 INFO [P2P] Our node has been full started. It took=321ms
2020-08-03T14:59:58 DEBUG [chain-verification] Querying for best block hash
2020-08-03T14:59:58 DEBUG [chain-verification] Querying for best block hash
2020-08-03T14:59:58 DEBUG [chain-verification] Looking for header by hash=DoubleSha256BDigestBE(0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)
2020-08-03T14:59:58 DEBUG [chain-verification] getHeader result: height=0, hash=DoubleSha256BDigestBE(0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206), chain work=2
2020-08-03T14:59:58 DEBUG [chain-verification] Querying for filter count
2020-08-03T14:59:58 DEBUG [chain-verification] Querying for filter header count
2020-08-03T14:59:58 INFO [P2P] Started node, best block hash 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 at height 0, with 0 filter headers and 0 filters
2020-08-03T14:59:58 DEBUG [chain-verification] Querying for best block hash
2020-08-03T14:59:58 DEBUG [P2P] Sending getcfcheckpt=GetCompactFilterCheckPointMessage(Basic,DoubleSha256Digest(06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f)) to peer Peer(localhost/127.0.0.1:18444)
2020-08-03T14:59:58 DEBUG [P2P] Sending msg=getcfcheckpt to peer=localhost/127.0.0.1:18444
2020-08-03T14:59:58 INFO [P2P] We've been disconnected by Peer(localhost/127.0.0.1:18444) command=PeerClosed
2020-08-03T14:59:58 DEBUG [P2P] Disconnected bitcoin peer=Peer(localhost/127.0.0.1:18444)
2020-08-03T14:59:58 INFO [HTTP] Started Bitcoin-S HTTP server at /127.0.0.1:9999
2020-08-03T14:59:58 INFO [HTTP] Starting neutrino node sync
2020-08-03T14:59:58 DEBUG [chain-verification] Querying for best block hash
2020-08-03T14:59:58 INFO [P2P] Starting sync node, height=0 hash=DoubleSha256BDigestBE(0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)
2020-08-03T14:59:58 DEBUG [P2P] Sending msg=getheaders to peer=localhost/127.0.0.1:18444
[INFO] [akkaDeadLetter][08/03/2020 09:59:58.878] [bitcoin-s-akka.actor.default-dispatcher-6] [akka://bitcoin-s/user/P2PClient$-1596466797934] Message [org.bitcoins.core.p2p.NetworkMessage$NetworkMessageImpl] to Actor[akka://bitcoin-s/user/P2PClient$-1596466797934#2132683720] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://bitcoin-s/user/P2PClient$-1596466797934#2132683720] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by Christewart** [comment] 2020-08-03 16:09
Looks like we are getting disconnected by bitcoind 

>2020-08-03T14:59:58 INFO [P2P] We've been disconnected by Peer(localhost/127.0.0.1:18444) command=PeerClosed
2020-08-03T14:59:58 DEBUG [P2P] Disconnected bitcoin peer=Peer(localhost/127.0.0.1:18444)

Anything interesting in the `~/.bitcoin/regtest/debug.log`?

**Comment by nkohen** [comment] 2020-08-03 19:43
From debug.log
```
2019-03-27 22:34:22 Bitcoin Core version v0.16.3 (release build)
2019-03-27 22:34:22 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2019-03-27 22:34:22 Assuming ancestors of block 0000000000000000005214481d2d96f898e3d5416e43359c145944a909d242e0 have valid signatures.
2019-03-27 22:34:22 Setting nMinimumChainWork=000000000000000000000000000000000000000000f91c579d57cad4bc5278cc
2019-03-27 22:34:22 Using the 'sse4' SHA256 implementation
2019-03-27 22:34:22 Using RdRand as an additional entropy source
2019-03-27 22:34:22 Default data directory /home/nkohen/.bitcoin
2019-03-27 22:34:22 Using data directory /home/nkohen/Desktop/SuredBits/temp/.
2019-03-27 22:34:22 Using config file /home/nkohen/Desktop/SuredBits/temp/./bitcoin.conf
2019-03-27 22:34:22 Using at most 125 automatic connections (1024 file descriptors available)
2019-03-27 22:34:22 Warning: relative datadir option '.' specified, which will be interpreted relative to the current working directory '/home/nkohen/Desktop/SuredBits/temp'. This is fragile, because if b
itcoin is started in the future from a different location, it will be unable to locate the current data files. There could also be data loss if bitcoin is started while in a temporary directory.
2019-03-27 22:34:22 Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2019-03-27 22:34:22 Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2019-03-27 22:34:22 Using 6 threads for script verification
2019-03-27 22:34:22 scheduler thread start
2019-03-27 22:34:22 HTTP: creating work queue of depth 16
2019-03-27 22:34:22 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpc
user for rpcauth auth generation.
2019-03-27 22:34:22 HTTP: starting 4 worker threads
2019-03-27 22:34:22 Using wallet directory /home/nkohen/Desktop/SuredBits/temp/.
2019-03-27 22:34:22 init message: Verifying wallet(s)...
2019-03-27 22:34:22 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2019-03-27 22:34:22 Using wallet wallet.dat
2019-03-27 22:34:22 CDBEnv::Open: LogDir=/home/nkohen/Desktop/SuredBits/temp/./database ErrorFile=/home/nkohen/Desktop/SuredBits/temp/./db.log
2019-03-27 22:34:22 Cache configuration:
2019-03-27 22:34:22 * Using 2.0MiB for block index database
2019-03-27 22:34:22 * Using 8.0MiB for chain state database
2019-03-27 22:34:22 * Using 440.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2019-03-27 22:34:22 init message: Loading block index...
2019-03-27 22:34:22 Opening LevelDB in /home/nkohen/Desktop/SuredBits/temp/./blocks/index
2019-03-27 22:34:22 Opened LevelDB successfully
2019-03-27 22:34:22 Using obfuscation key for /home/nkohen/Desktop/SuredBits/temp/./blocks/index: 0000000000000000
2019-03-27 22:34:22 LoadBlockIndexDB: last block file = 0
2019-03-27 22:34:22 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=0, size=0, heights=0...0, time=1970-01-01...1970-01-01)
2019-03-27 22:34:22 Checking all blk files are present...
2019-03-27 22:34:22 LoadBlockIndexDB: transaction index disabled
2019-03-27 22:34:22 Initializing databases...
2019-03-27 22:34:22 Pre-allocating up to position 0x1000000 in blk00000.dat
2019-03-27 22:34:22 Opening LevelDB in /home/nkohen/Desktop/SuredBits/temp/./chainstate
2019-03-27 22:34:22 Opened LevelDB successfully
2019-03-27 22:34:22 Wrote new obfuscate key for /home/nkohen/Desktop/SuredBits/temp/./chainstate: 6f87fe104e83e57d
2019-03-27 22:34:22 Using obfuscation key for /home/nkohen/Desktop/SuredBits/temp/./chainstate: 6f87fe104e83e57d
2019-03-27 22:34:22 init message: Rewinding blocks...
2019-03-27 22:34:22  block index              76ms
2019-03-27 22:34:22 init message: Loading wallet...
2019-03-27 22:34:22 nFileVersion = 160300
2019-03-27 22:34:22 Keys: 0 plaintext, 0 encrypted, 0 w/ metadata, 0 total
2019-03-27 22:34:22 Performing wallet upgrade to 60000
2019-03-27 22:34:23 keypool added 2000 keys (1000 internal), size=2000 (1000 internal)
2019-03-27 22:34:23  wallet                  811ms
2019-03-27 22:34:23 setKeyPool.size() = 2000
2019-03-27 22:34:23 mapWallet.size() = 0
2019-03-27 22:34:23 mapAddressBook.size() = 0
2019-03-27 22:34:23 UpdateTip: new best=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f height=0 version=0x00000001 log2_work=32.000022 tx=1 date='2009-01-03 18:15:05' progress=0.000000 c
ache=0.0MiB(0txo)
2019-03-27 22:34:23 Failed to open mempool file from disk. Continuing anyway.
2019-03-27 22:34:23 mapBlockIndex.size() = 1
2019-03-27 22:34:23 nBestHeight = 0
2019-03-27 22:34:23 AddLocal([2601:282:4101:9356::9d0d]:8333,1)
2019-03-27 22:34:23 torcontrol thread start
2019-03-27 22:34:23 Discover: IPv6 wlp59s0: 2601:282:4101:9356::9d0d
2019-03-27 22:34:23 AddLocal([2601:282:4101:9356:1ce9:a35b:a2da:42fd]:8333,1)
2019-03-27 22:34:23 Discover: IPv6 wlp59s0: 2601:282:4101:9356:1ce9:a35b:a2da:42fd
2019-03-27 22:34:23 AddLocal([2601:282:4101:9356:8cd4:b328:39a1:8cab]:8333,1)
2019-03-27 22:34:23 Discover: IPv6 wlp59s0: 2601:282:4101:9356:8cd4:b328:39a1:8cab
2019-03-27 22:34:23 Bound to [::]:8333
2019-03-27 22:34:23 Bound to 0.0.0.0:8333
2019-03-27 22:34:23 init message: Loading P2P addresses...
2019-03-27 22:34:23 ERROR: DeserializeFileDB: Failed to open file /home/nkohen/Desktop/SuredBits/temp/./peers.dat
2019-03-27 22:34:23 Invalid or missing peers.dat; recreating
2019-03-27 22:34:23 init message: Loading banlist...
2019-03-27 22:34:23 ERROR: DeserializeFileDB: Failed to open file /home/nkohen/Desktop/SuredBits/temp/./banlist.dat
2019-03-27 22:34:23 Invalid or missing banlist.dat; recreating
2019-03-27 22:34:23 init message: Starting network threads...
2019-03-27 22:34:23 net thread start
2019-03-27 22:34:23 opencon thread start
2019-03-27 22:34:23 init message: Done loading
2019-03-27 22:34:23 addcon thread start
2019-03-27 22:34:23 msghand thread start
2019-03-27 22:34:23 dnsseed thread start
2019-03-27 22:34:23 Loading addresses from DNS seeds (could take a while)
2019-03-27 22:34:25 New outbound peer connected: version: 70015, blocks=569080, peer=0
2019-03-27 22:34:25 New outbound peer connected: version: 70015, blocks=569080, peer=1
2019-03-27 22:34:25 204 addresses found from DNS seeds
2019-03-27 22:34:25 dnsseed thread exit
2019-03-27 22:34:26 New outbound peer connected: version: 70015, blocks=569080, peer=2
2019-03-27 22:34:26 New outbound peer connected: version: 70015, blocks=569080, peer=3
2019-03-27 22:34:29 New outbound peer connected: version: 70015, blocks=569080, peer=4
2019-03-27 22:34:33 New outbound peer connected: version: 70015, blocks=569080, peer=5
2019-03-27 22:34:33 New outbound peer connected: version: 70015, blocks=569080, peer=6
2019-03-27 22:34:34 New outbound peer connected: version: 70015, blocks=569080, peer=7
2019-03-27 22:34:37 tor: Thread interrupt
2019-03-27 22:34:37 Shutdown: In progress...
2019-03-27 22:34:37 addcon thread exit
2019-03-27 22:34:37 torcontrol thread exit
2019-03-27 22:34:37 opencon thread exit
2019-03-27 22:34:37 net thread exit
2019-03-27 22:34:37 msghand thread exit
2019-03-27 22:34:37 scheduler thread interrupt
2019-03-27 22:34:37 Dumped mempool: 1.1e-05s to copy, 0.006091s to dump
2019-03-27 22:34:38 Shutdown: done
```

**Comment by benthecarman** [comment] 2020-08-03 21:06
On `master` if I do a fresh regtest network and fresh bitcoin-s db. It automatically syncs for me.

Is it possible that you have your old regtest bitcoin-s db so it's requesting the wrong headers

**Comment by nkohen** [comment] 2020-08-04 14:52
Don't believe so, I deleted all regtest folders before starting

**Comment by Christewart** [comment] 2020-08-04 20:05
Ok, I am running fresh regtest on  7db465f2226e8c12e6c60ff6d5c9871ab1364210 with `--datadir /tmp/tmp-bitcoin-s`

## Solution

Here is the answer: 

https://github.com/bitcoin-s/bitcoin-s/issues/1741#issuecomment-668804538

## Config 
My bitcoin.conf file:

```
addresstype=bech32
server=1
rpcuser=user
rpcpassword=pass
blockfilterindex=1
txindex=1
daemon=1
debug=1
#lnd 
#zmqpubrawblock=tcp://127.0.0.1:28332
#zmqpubrawtx=tcp://127.0.0.1:28333

zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
```

initial bitcoind chain state before starting the node

```
./bitcoin-cli -regtest getblockchaininfo
{
  "chain": "regtest",
  "blocks": 108,
  "headers": 108,
  "bestblockhash": "5ca5232c1da5ffac1cb3a2bf4bb99740398eea725c9f27d93ccab7635fe42d17",
  "difficulty": 4.656542373906925e-10,
  "mediantime": 1596568227,
  "verificationprogress": 1,
  "initialblockdownload": false,
  "chainwork": "00000000000000000000000000000000000000000000000000000000000000da",
  "size_on_disk": 32936,
  "pruned": false,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": false,
      "height": 500
    },
    "bip66": {
      "type": "buried",
      "active": false,
      "height": 1251
    },
    "bip65": {
      "type": "buried",
      "active": false,
      "height": 1351
    },
    "csv": {
      "type": "buried",
      "active": false,
      "height": 432
    },
    "segwit": {
      "type": "buried",
      "active": true,
      "height": 0
    },
    "testdummy": {
      "type": "bip9",
      "bip9": {
        "status": "defined",
        "start_time": 0,
        "timeout": 9223372036854775807,
        "since": 0
      },
      "active": false
    }
  },
  "warnings": ""
}
```

My `bitcoin-s.conf` 

```
bitcoin-s {
    datadir = /tmp/tmp-bitcoin-s
    network = regtest# regtest, testnet3, mainnet

    logging {
        level = DEBUG# trace, debug, info, warn, error, off

        # You can also tune specific module loggers.
        # They each take the same levels as above.
        # If they are commented out (as they are
        # by default), `logging.level` gets used
        # instead.
        # The available loggers are:

        # incoming and outgoing P2P messages
         p2p = DEBUG 

        # verification of block headers, merkle trees
         chain-verification = DEBUG 

        # generation of addresses, signing of TXs
        # key-handling = info

        # wallet operations not related to key management
        wallet = debug

        # HTTP RPC server
        http = DEBUG 

        # Database interactions
         database = DEBUG 

        # whether or not to write to the log file
        disable-file = false

        # whether or not to log to stdout
        disable-console = false
    }

    node {
        peers = ["127.0.0.1:18444"] # a list of peer addresses in form "hostname:portnumber"
                              # (e.g. "localhost:18444")
                              # (e.g. "neutrino.testnet3.suredbits.com:18333")
                              # (e.g. "neutrino.suredbits.com:8333")
                              # Port number is optional, the default value is 8333 for mainnet,
                              # 18333 for testnet and 18444 for regtest.
        mode = neutrino# neutrino, spv
    }

    chain {
        neutrino {
            filter-header-batch-size = 2000
            filter-batch-size = 100
        }
    }

    # settings for wallet module
    wallet {
        defaultAccountType = segwit# legacy, segwit, nested-segwit

        bloomFalsePositiveRate = 0.0001 # percentage
    }
    server {
#    	rpcport=12344
    }
   common {
        profile = "slick.jdbc.SQLiteProfile$"
        db {
            url = "jdbc:postgresql://localhost:5432/database"
            driver = "org.postgresql.Driver"
            username = "user"
            password = "topsecret"
        }
    }
}
akka {

    loglevel = "INFO"
    stdout-loglevel = "INFO"

    actor {
        debug {
            # enable DEBUG logging of all AutoReceiveMessages (Kill, PoisonPill etc.)
            autoreceive= off
            # enable function of LoggingReceive, which is to log any received message at
            # DEBUG level
            receive = on
            # enable DEBUG logging of unhandled messages
            unhandled = off

            # enable DEBUG logging of actor lifecycle changes
            lifecycle = off

            event-stream=off
        }
    }

    #https://doc.akka.io/docs/akka-http/current/configuration.html
}
```

## Running 

When I run with this configuration, ironically I do sync all headers, but I actually don't sync filters. I guess this is sort of helping you, (as my undersatnding is you can't sync headers either)

Here is what I endup with as my node state

>➜  bin git:(master) ✗ ./bitcoin-s-cli getblockcount
108
➜  bin git:(master) ✗ ./bitcoin-s-cli getfiltercount
0
➜  bin git:(master) ✗ ./bitcoin-s-cli getfilterheadercount
0

## Logs

https://pastebin.com/4Ce5Whxh

**Comment by Christewart** [comment] 2020-08-04 20:18
So in the comment above I was running an incorrect instance of bitcoind (0.19.0.1) that does not have neutrino support. When I run with our bitcoind binary that supports neutrino (0.18.99) I can reproduce this issue and from years of pain and suffering I know what the problem is: 

### Starting a regtest node on the 0.18.x bitcoind series (does this exist on others??)

When starting a regtest node, if you look at `getblockchaininfo` you will see 

>./bitcoin-cli -regtest getblockchaininfo
{
  "chain": "regtest",
  "blocks": 123,
  "headers": 123,
  "bestblockhash": "51975aad1828aa9acec93bcac68466d5438cafd76f8878adb8561e35302c2d3c",
  "difficulty": 4.656542373906925e-10,
  "mediantime": 1595281633,
  "verificationprogress": 1,
  "initialblockdownload": true,
  ...
}

The key thing here is `"initialblockdownload":true`. When we are in IBD, a bitcoind node will not serve data to other peers. You need to generate a block on regtest to get out of IBD. When I generate a block on bitcoind, and then shutdown my server and restart my bitcoin-s-server things work. 

```
➜  bin git:(master) ✗ ./bitcoin-s-cli getblockcount                                                  
124
➜  bin git:(master) ✗ ./bitcoin-s-cli getfiltercount
124
➜  bin git:(master) ✗ ./bitcoin-s-cli getfilterheadercount
124
```

**Comment by nkohen** [comment] 2020-08-04 21:58
Sadly this does not resolve my issue where I believe the relevant bitcoin-s log is
```
2020-08-04T21:56:40 INFO [P2P] Starting sync node, height=0 hash=DoubleSha256BDigestBE(0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)
2020-08-04T21:56:40 DEBUG [P2P] Sending msg=getheaders to peer=localhost/127.0.0.1:18444
[INFO] [akkaDeadLetter][08/04/2020 16:56:40.370] [bitcoin-s-akka.actor.default-dispatcher-5] [akka://bitcoin-s/user/P2PClient$-1596578199485] Message [org.bitcoins.core.p2p.NetworkMessage$NetworkMessageImpl] to Actor[akka://bitcoin-s/user/P2PClient$-1596578199485#-1893214650] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://bitcoin-s/user/P2PClient$-1596578199485#-1893214650] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```
and I also have an interesting line at the end of my bitcoind debug.log:
```
2020-08-04T21:55:49Z Adding fixed seed nodes as DNS doesn't seem to be available.
```
but I'm not sure that that one is relevant.

**Comment by nkohen** [comment] 2020-08-04 22:02
Using `127.0.0.1` instead of `localhost` I now get
```
2020-08-04T22:00:51 INFO [P2P] Starting sync node, height=0 hash=DoubleSha256BDigestBE(0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)
2020-08-04T22:00:51 DEBUG [P2P] Sending msg=getheaders to peer=/127.0.0.1:18444
[INFO] [akkaDeadLetter][08/04/2020 17:00:51.714] [bitcoin-s-akka.actor.default-dispatcher-6] [akka://bitcoin-s/user/P2PClient$-1596578450832] Message [org.bitcoins.core.p2p.NetworkMessage$NetworkMessageImpl] to Actor[akka://bitcoin-s/user/P2PClient$-1596578450832#-831928548] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://bitcoin-s/user/P2PClient$-1596578450832#-831928548] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
^C2020-08-04T22:00:56 INFO [P2P] Stopping node
[INFO] [akkaDeadLetter][08/04/2020 17:00:56.216] [bitcoin-s-akka.actor.default-dispatcher-6] [akka://bitcoin-s/user/P2PClient$-1596578450832] Message [org.bitcoins.node.networking.P2PClient$IsConnected$] to Actor[akka://bitcoin-s/user/P2PClient$-1596578450832#-831928548] was not delivered. [2] dead letters encountered. If this is not an expected behavior then Actor[akka://bitcoin-s/user/P2PClient$-1596578450832#-831928548] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
2020-08-04T22:00:56 WARN [P2P] Cannot disconnect client that is not connected to socket=/127.0.0.1:18444!
2020-08-04T22:00:56 INFO [P2P] Awaiting disconnect
```
and no debug logs on bitcoind

**Comment by nkohen** [comment] 2020-08-04 22:03
oh no wait that is the same thing as last time but with localhost replaced by 127.0.0.1

**Comment by nkohen** [comment] 2020-08-04 22:09
Getting this now when using `127.0.0.1` instead of `localhost`, not sure if I was getting it before or not:
```
2020-08-04T22:05:58 DEBUG [P2P] Sending msg=getcfcheckpt to peer=/127.0.0.1:18444
2020-08-04T22:05:58 INFO [P2P] We've been disconnected by Peer(/127.0.0.1:18444) command=PeerClosed
2020-08-04T22:05:58 DEBUG [P2P] Disconnected bitcoin peer=Peer(/127.0.0.1:18444)
```
Still just that one log showing up in bitcoind debug.log ^

**Comment by nkohen** [comment] 2020-08-04 23:49
After ctrl + C:
```
[INFO] [akkaDeadLetter][08/04/2020 17:18:33.301] [bitcoin-s-akka.actor.default-dispatcher-7] [akka://bitcoin-s/user/P2PClient$-1596579512338] Message [org.bitcoins.core.p2p.NetworkMessage$NetworkMessageImpl] to Actor[akka://bitcoin-s/user/P2PClient$-1596579512338#1182536788] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://bitcoin-s/user/P2PClient$-1596579512338#1182536788] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
^C2020-08-04T22:21:37 INFO [P2P] Stopping node
[INFO] [akkaDeadLetter][08/04/2020 17:21:37.352] [bitcoin-s-akka.actor.default-dispatcher-15] [akka://bitcoin-s/user/P2PClient$-1596579512338] Message [org.bitcoins.node.networking.P2PClient$IsConnected$] to Actor[akka://bitcoin-s/user/P2PClient$-1596579512338#1182536788] was not delivered. [2] dead letters encountered. If this is not an expected behavior then Actor[akka://bitcoin-s/user/P2PClient$-1596579512338#1182536788] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
2020-08-04T22:21:37 WARN [P2P] Cannot disconnect client that is not connected to socket=/127.0.0.1:18444!
2020-08-04T22:21:37 INFO [P2P] Awaiting disconnect
[INFO] [akkaDeadLetter][08/04/2020 17:21:37.356] [bitcoin-s-akka.actor.default-dispatcher-15] [akka://bitcoin-s/user/P2PClient$-1596579512338] Message [org.bitcoins.node.networking.P2PClient$IsDisconnected$] to Actor[akka://bitcoin-s/user/P2PClient$-1596579512338#1182536788] was not delivered. [3] dead letters encountered. If this is not an expected behavior then Actor[akka://bitcoin-s/user/P2PClient$-1596579512338#1182536788] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
2020-08-04T22:21:37 INFO [P2P] Node stopped! It took=4ms
[WARN] [08/04/2020 17:21:37.363] [shutdownHook1] [CoordinatedShutdown(akka://bitcoin-s)] Could not addJvmShutdownHook, due to: Shutdown in progress
```

**Comment by benthecarman** [comment] 2020-08-05 15:06
Issue was resolved by adding `blockfilterindex=1` to the `bitcoin.conf`

**Closed as completed** 2020-08-05 15:06 UTC
Labels: bug, node, neutrino
